### ISSUE TITLE
Secure Websockets

### ISSUE THREAD

**Issue by cjmurph** [cagdasdoner/maqiatto#1]
Hi, just wondering if you have any plans to add secure websocket connectivity? Thanks.

**Comment by cagdasdoner** [comment]
Hi, do you need it only on client implementation or want to connect to maqiatto.com via secure websockets?

**Comment by cjmurph** [comment]
I wanted to connect to maqiatto.com via secure web socket. I'm using a javascript client in a static web page, the page is secure so I can't mix that with an insecure web socket connection to maqiatto.com

**Comment by cagdasdoner** [comment]
Maqiatto provides secure websocket mqtt connections on port 4883. But notice that free public broker only uses self signed certificates which will need to be validated on your browser manually. For a CA signed one, you should use at least tier 2 from the subscriptions. See pricing tab on the menu.
Thanks.

**Comment by cjmurph** [comment]
No problem, thanks!
