### ISSUE TITLE
Correct parameters to connect to maqiatto MQTT broker

### ISSUE THREAD

**Issue by MichaelNewham** [cagdasdoner/maqiatto#2]
Hi there,

Am following these instructions at [https://www.dfrobot.com/blog-1080.html ](https://www.dfrobot.com/blog-1080.html) to connect an **Obloq ESP-8266** via Serial Port on Arduino IDE. 
I can connect to local network fine by issuing following command >

`|2|1|<SSID>,<PASSWORD>|`

But when i try to connect to 'maqiatto MQTT Broker' with this command >

`|4|1|1|maqiatto.com|1883|<emailaddress/topic>|<PASSWORD>|`

.. I get the following error >

`|4|1|1|2|Not authorized to connect`

The four parameters required are **Server, Port, Topic** and **Password** which i've supplied.

I've already tested my 'broker configuration' at your [MQTT over Websocket test page](http://maqiatto.com/webclient).

Should i try a different port or something?

Cheers,  Michael.

![2021-04-28_19-37](https://user-images.githubusercontent.com/11710523/116455762-5e257180-a859-11eb-96d8-633a6a6baee0.png)

**Comment by cagdasdoner** [comment]
@MichaelNewham Not a dfrobot fan but according to the documentation you should provide username into the command 4 | 1 which will be your e-mail, not the topic : 

|4|1|1|server|port|user|password|

Sample command might be : 

|4|1|1|maqiatto.com|1883|YOUR_EMAIL_ADDRESS_HERE|YOUR_PASSWORD_HERE|
